export const Icons = {   
    icon_full_name: require("@assets/images/icon/ic_full_name.png"),
    icon_full_name_add: require("@assets/images/icon/ic_full_name_add.png"),
    icon_cpf: require("@assets/images/icon/ic_cpf.png"),
    icon_cardnumber: require("@assets/images/icon/ic_cardnumber.png"),
    icon_email: require("@assets/images/icon/ic_email.png"),
    icon_password: require("@assets/images/icon/ic_password.png"),
    icon_refresh_head : require("@assets/images/icon/ic_refresh_head.png"),
    icon_refresh_body : require("@assets/images/icon/ic_refresh_body.png"),
    icon_digital : require("@assets/images/icon/ic_digital.png"),
    icon_tooth : require("@assets/images/icon/ic_tooth.png"),
    icon_filter : require("@assets/images/icon/ic_filter.png"),
    icon_filter_verse : require("@assets/images/icon/ic_filter_verse.png"),
    icon_dollar : require("@assets/images/icon/ic_dollar.png"),
    icon_couple_user : require("@assets/images/icon/ic_couple_user.png"),
    icon_star : require("@assets/images/icon/ic_star.png"),
    icon_flat : require("@assets/images/icon/ic_flat.png"),
    icon_setting : require("@assets/images/icon/ic_setting.png"),
    icon_logout : require("@assets/images/icon/ic_log_out.png"),
    icon_leftclose : require("@assets/images/icon/ic_leftclose.png"),
    icon_left_arrow : require("@assets/images/icon/ic_left_arrow.png"),
    icon_search : require("@assets/images/icon/ic_search.png"),
    icon_save : require("@assets/images/icon/ic_save.png"),
    icon_gender : require("@assets/images/icon/ic_gender.png"),
    icon_new : require("@assets/images/icon/ic_new.png"),
    icon_calendar : require("@assets/images/icon/ic_calendar.png"),
    icon_folder : require("@assets/images/icon/ic_folder.png"),
    icon_service : require("@assets/images/icon/ic_service.png"),
    icon_delete : require("@assets/images/icon/delete.png"),
    icon_deliver_user : require("@assets/images/icon/ic_deliver_user.png"),
    icon_address : require("@assets/images/icon/ic_address.png"),
    icon_code : require("@assets/images/icon/ic_code.png"),
    icon_city : require("@assets/images/icon/ic_city.png"),
    icon_local : require("@assets/images/icon/ic_local.png"),
    icon_edit : require("@assets/images/icon/ic_edit.png"),
    icon_ins : require("@assets/images/icon/ins.png"),
  };
  