export const Images = {
    logo: require("@assets/images/logo.png"),
    inside: require("@assets/images/inside.png"),
    live: require("@assets/images/live.png"),
    splash: require("@assets/images/splash.jpg"),
    signin_back : require("@assets/images/signin_back.png"),
    signin_usericon : require("@assets/images/signin_usericon.png"),
    signup_icon : require("@assets/images/signup_icon.png"),   
    tooth_01 : require("@assets/images/tooth/01.png"),   
    tooth_02 : require("@assets/images/tooth/02.png"), 
    tooth_03 : require("@assets/images/tooth/03.png"),     
    tooth_04 : require("@assets/images/tooth/04.png"),   
    tooth_05 : require("@assets/images/tooth/05.png"),   
    tooth_06 : require("@assets/images/tooth/06.png"),   
    tooth_07 : require("@assets/images/tooth/07.png"),   
    tooth_08 : require("@assets/images/tooth/08.png"),   
    tooth_09 : require("@assets/images/tooth/09.png"),   
    tooth_10 : require("@assets/images/tooth/10.png"),   
    tooth_11 : require("@assets/images/tooth/11.png"),   
    tooth_12 : require("@assets/images/tooth/12.png"),   
    tooth_13 : require("@assets/images/tooth/13.png"),   
    tooth_14 : require("@assets/images/tooth/14.png"),   
    tooth_15 : require("@assets/images/tooth/15.png"),   
    tooth_16 : require("@assets/images/tooth/16.png"),   
    tooth_17 : require("@assets/images/tooth/17.png"),
    tooth_18 : require("@assets/images/tooth/18.png"),      
    tooth_19 : require("@assets/images/tooth/19.png"),   
    tooth_20 : require("@assets/images/tooth/20.png"),   
    tooth_21 : require("@assets/images/tooth/21.png"),   
    tooth_22 : require("@assets/images/tooth/22.png"),   
    tooth_23 : require("@assets/images/tooth/23.png"),   
    tooth_24 : require("@assets/images/tooth/24.png"),   
    tooth_25 : require("@assets/images/tooth/25.png"),   
    tooth_26 : require("@assets/images/tooth/26.png"),   
    tooth_27 : require("@assets/images/tooth/27.png"),   
    tooth_28 : require("@assets/images/tooth/28.png"),   
    tooth_29 : require("@assets/images/tooth/29.png"),   
    tooth_30 : require("@assets/images/tooth/30.png"),   
    tooth_31 : require("@assets/images/tooth/31.png"),   
    tooth_32 : require("@assets/images/tooth/32.png"),   
  };
  